return {
  	book    = "Ephesians",
    version = "NASB 95",
  	chapters = {
        {   chapter = 1,
            verses  = {
                {   verse = 1,
                    "Paul, an apostle of Christ Jesus by the will of God,",
                    "To the saints who are at Ephesus and who are faithful in Christ Jesus:",
                },
                {   verse = 2,
                    "Grace to you and peace from God our Father and the Lord Jesus Christ.",
                },
                {   verse = 3,
                    "Blessed be the God and Father of our Lord Jesus Christ,",
                    "who has blessed ME with every spiritual blessing in the heavenly places in Christ,",   
                },                                
                {   verse = 4,
                    "just as He chose ME in Him before the foundation of the world,",
                    "that I would be holy and blameless before Him.",
                    "In love",
                },
                {   verse = 5,
                    "He predestined ME to adoption as A SON through Jesus Christ to Himself,",
                    "according to the kind intention of His will,",
                },
                {   verse = 6,
                    "to the praise of the glory of His grace,",
                    "which He freely bestowed on ME in the Beloved.",
                },
                {   verse = 7,
                    "In Him I have redemption through His blood,",
                    "the forgiveness of MY trespasses,",
                    "according to the riches of His grace",
                },
                {   verse = 8,
                    "which He lavished on ME.",
                    "In all wisdom and insight",
                },
                {   verse = 9,
                    "He made known to ME the mystery of His will,",
                    "according to His kind intention which He purposed in Him",
                },
                {   verse = 10,
                    "with a view to an administration suitable to the fullness of the times,",
                    "that is, the summing up of all things in Christ,",
                    "things in the heavens and things on the earth.",
                    "In Him",
                },
                {   verse = 11,
                    "also I have obtained an inheritance,",
                    "having been predestined according to His purpose",
                    "who works all things after the counsel of His will,"
                },
                {   verse = 12,
                    "to the end that I who WAS the first to hope in Christ would be to the praise of His glory." 
                },
                {   verse = 13,
                    "In Him, I also, after listening to the message of truth, the gospel of MY salvation -",
                    "having also believed, I WAS sealed in Him with the Holy Spirit of promise,",
                },
                {   verse = 14,
                    "who is given as a pledge of MY inheritance with a view to the redemption of God's own possession,",
                    "to the praise of His glory.",
                },
                {   verse = 15,
                    "For this reason I too, having heard of the faith in the Lord Jesus",
                    "which exists among you and your love for all the saints,",
                }, 
                {   verse = 16,
                    "do not cease giving thanks for you,",
                    "while making mention of you in my prayers;",
                },
                {   verse = 17,
                    "that the God of our Lord Jesus Christ,",
                    "the Father of glory, may give to you a spirit of wisdom",
                    "and of revelation in the knowledge of Him.",
                },
                {   verse = 18,
                    "I pray that the eyes of your heart may be enlightened,",
                    "so that you will know what is the hope of His calling,",
                    "what are the riches of the glory of His inheritance in the saints,",
                },
                {   verse = 19,
                    "and what is the surpassing greatness of His power toward us who believe.",
                    "These are in accordance with the working of the strength of His might",
                },
                {   verse = 20,
                    "which He brought about in Christ,",
                    "when He raised Him from the dead and seated Him at His right hand in the heavenly places,"
                },
                {   verse = 21,
                    "far above all rule and authority and power and dominion,",
                    "and every name that is named, not only in this age but also in the one to come.",
                },
                {   verse = 22,
                    "And He put all things in subjection under His feet,",
                    "and gave Him as head over all things to the church,",
                },
                {   verse = 23,
                    "which is His body, the fullness of Him who fills all in all.", 
                },
            },
        },
    },
}
        
