return {
    book     = "Romans",
    version  = "NASB 95",
    chapters = {
        {   chapter = 8,
            verses = {
                {   verse = 1,
                    "Therefore there is now no condemnation for those who are in Christ Jesus.",
                },
            },
        },
        {   chapter = 11,
            verses = {
                {   verse = 33,
                    "Oh, the depth of the riches both of the wisdom and knowledge of God!",
                    "How unsearchable are His judgments and unfathomable His ways!",
                },
                {   verse = 34,
                    "For WHO HAS KNOWN THE MIND OF THE LORD, OR WHO BECAME HIS COUNSELOR?",
                },
                {   verse = 35,
                    "Or WHO HAS FIRST GIVEN TO HIM THAT IT MIGHT BE PAID BACK TO Him AGAIN?",
                },
                {   verse = 36,
                    "For from Him and through Him and to Him are all things.",
                    "To Him be the glory forever. Amen.",
                },
            },
        },
        {   chapter = 12,
            verses = {
                {   verse = 1,
                    "Therefore I urge you, brethren, by the mercies of God,",
                    "to present your bodies a living and holy sacrifice,",
                    "acceptable to God, which is your spiritual service of worship.",
                },
                {   verse = 2,
                    "And do not be conformed to this world,",
                    "but be transformed by the renewing of your mind,",
                    "so that you may prove what the will of God is,",
                    "that which is good and acceptable and perfect.",
                },
            },
        },
    },
}
